export const certificates = [
  {id:"be10x",title:"AI Tools & ChatGPT Workshop",issuer:"be10x Academy",date:"Feb 08, 2026",year:2026,category:"Professional",desc:"Hands-on workshop: create presentations, analyse data & code with AI in minutes.",proof:"Mastery of modern AI toolstack for 10x productivity.",vid:"BE10X-VERIFIED-2026",img:"photo8261229449771822727.webp",featured:true},
  {id:"plutus",title:"Certificate in Finance Career Pathways",issuer:"Plutus Education",date:"May 20, 2026",year:2026,category:"Professional",desc:"Career-focused program on finance fundamentals.",proof:"Shows structured understanding of finance careers.",vid:"PLUTUS-FCP-26",img:"photo5499857257153579581.webp",featured:true},
  {id:"stock",title:"Certificate of Achievement - Stock Market & Investing",issuer:"Finance & Investment Academy",date:"May 08, 2024",year:2024,category:"Professional",desc:"Successfully completed course on Stock Market & Investing - strong understanding of financial markets, investment strategies, risk management, and portfolio building.",proof:"Proves dedicated financial literacy, investment strategy knowledge and commitment to financial growth.",vid:"STOCK-INV-08MAY2024",img:"photo3372206564304656693.webp",featured:true},
  {id:"outskill-genai",title:"Generative AI Mastermind",issuer:"Outskill",date:"Dec 12, 2024",year:2024,category:"Professional",desc:"Intensive cohort on LLMs, prompt engineering & AI workflows.",proof:"Proves ability to build production-grade GenAI solutions.",vid:"OUTSKILL-GAIM-24",img:"photo4958118504668522423.webp",featured:true},
  {id:"html",title:"Course Certificate - HTML",issuer:"Sololearn - Yeva Hyusyan, CEO",date:"Aug 14, 2020",year:2020,category:"Professional",desc:"Successfully completed HTML course by demonstrating theoretical understanding of HTML.",proof:"Validates core web development fundamentals - foundation for your portfolio site.",vid:"CT-LCKXOHEU",img:"photo739890860221712527.webp",featured:false},
  {id:"vivekanand",title:"Swami Vivekanand Quiz - National Youth Day",issuer:"Govt. P.G. College, Guna (M.P.) - NSS Girls Unit",date:"Jan 12, 2021",year:2021,category:"Achievements",desc:"National Youth Day online quiz on Swami Vivekanand.",proof:"Cultural literacy & academic engagement.",vid:"BYARFK-CE000022",img:"photo2695317192960784748.webp",featured:false},
  {id:"gandhi",title:"Mahatma Gandhi Quiz - 151st Birth Anniversary",issuer:"Govt. P.G. College, Guna (M.P.) - NSS",date:"Oct 02, 2020",year:2020,category:"Achievements",desc:"Online quiz on Mahatma Gandhi organized by NSS Unit.",proof:"Civic awareness & respect for national heritage.",vid:"VRWMHS-CE000216",img:"photo895755719422670651.webp",featured:false},
  {id:"covid",title:"Quiz Contest on Covid-19",issuer:"Govt. Chhatrasal College, Pichhore",date:"Jun 14, 2020",year:2020,category:"Skills",desc:"Quiz Contest on Covid-19 by Dept. of Sanskrit.",proof:"Health literacy & responsible citizenship.",vid:"BEDJPA-CE000485",img:"photo8935098468182624873.webp",featured:false},
  {id:"yoga",title:"Online Yoga Awareness Quiz Contest-2020",issuer:"Govt. Chhatrasal College - 6th International Yoga Day",date:"Jun 21, 2020",year:2020,category:"Skills",desc:"Yoga Awareness Quiz on occasion of International Yoga Day.",proof:"Commitment to holistic wellness.",vid:"YOGA-IYD-2020",img:"photo534127674968509719.webp",featured:false}
];
